services:
  mysql-db:
    container_name: mysql-db-container
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: EAOR.Db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql

  eaor-ui:
    container_name: eaor-ui-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - mysql-db
    restart: on-failure
    
volumes:
  my-db:
